---
title: "INLA scale code study"
author: "Hashan Fernando"
date: "2024-03-06"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(INLA)   
mat_crowd <- as.matrix(read.csv("Qmatrix_EP_CROWD.csv", header = TRUE))
mat_disabl <- as.matrix(read.csv("Qmatrix_EP_DISABL.csv", header = TRUE))
mat_limeng <- as.matrix(read.csv("Qmatrix_EP_LIMENG.csv", header = TRUE))
mat_pci <- as.matrix(read.csv("Qmatrix_EP_PCI.csv", header = TRUE))
mat_uninsur <- as.matrix(read.csv("Qmatrix_EP_UNINSUR.csv", header = TRUE))

```


```{r}
my_function <- function (Q, constr = NULL, eps = sqrt(.Machine$double.eps)) 
{
    marg.var <- rep(0, nrow(Q))
    Q <- inla.as.sparse(Q)
    g <- inla.read.graph(Q)
    for (k in seq_len(g$cc$n)) {
        i <- g$cc$nodes[[k]]
        n <- length(i)
        QQ <- Q[i, i, drop = FALSE]
        if (n == 1) {
            QQ[1, 1] <- 1
            marg.var[i] <- 1
        }
        else {
            cconstr <- constr
            if (!is.null(constr)) {
                cconstr$A <- constr$A[, i, drop = FALSE]
                eeps <- eps
            }
            else {
                eeps <- 0
            }
            idx.zero <- which(rowSums(abs(cconstr$A)) == 0)
            if (length(idx.zero) > 0) {
                cconstr$A <- cconstr$A[-idx.zero, , drop = FALSE]
                cconstr$e <- cconstr$e[-idx.zero]
            }
            res <- inla.qinv(QQ + Diagonal(n) * max(diag(QQ)) * 
                eeps, constr = cconstr)
            fac <- exp(mean(log(diag(res))))
            QQ <- fac * QQ
            marg.var[i] <- diag(res)/fac
        }
        
        #print(Q)
        #print(QQ)
        Q[i, i] <- QQ
        #print(Q)
    }
    return(list(Q = Q, var = marg.var, fac=fac))
}
```

```{r}
INLA_mat_crowd = my_function(mat_crowd, constr=list(A=matrix(1, nrow=1, ncol=12),e=0))
INLA_mat_disabl = my_function(mat_disabl, constr=list(A=matrix(1, nrow=1, ncol=11),e=0))
INLA_mat_limeng = my_function(mat_limeng, constr=list(A=matrix(1, nrow=1, ncol=16),e=0))
INLA_mat_pci = my_function(mat_pci, constr=list(A=matrix(1, nrow=1, ncol=10),e=0))
INLA_mat_uninsur = my_function(mat_uninsur, constr=list(A=matrix(1, nrow=1, ncol=8),e=0))

```
```{r}
INLA_mat_crowd$fac
INLA_mat_crowd$var
det(mat_crowd)
```
```{r}
INLA_mat_disabl$fac
INLA_mat_disabl$var
det(mat_disabl)
```

```{r}
INLA_mat_limeng$fac
INLA_mat_limeng$var
det(mat_limeng)
```

```{r}
INLA_mat_pci$fac
INLA_mat_pci$var
det(mat_pci)
```

```{r}
INLA_mat_uninsur$fac
INLA_mat_uninsur$var
det(mat_uninsur)

```



```{r}
exp(mean(log(T$var)))
```
