---
title: "INLA scale code study"
author: "Hashan Fernando"
date: "2024-03-06"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(INLA)   
df <- read.csv("Qmatrix_EP_DISABL.csv", header = TRUE)

mat <- as.matrix(df)
mat
```

inla.scale.model Study
\

define 12 element vector of 0 \ 
rep() function is used to replicate elements of vectors or array \

```{r}
marg.var <- rep(0, nrow(mat))
marg.var
```

```{r}
Q_sparse <- inla.as.sparse(mat)
Q_sparse
```
```{r}
g <- inla.read.graph(Q_sparse)
plot(g)
```

```{r}
constr=list(A=matrix(1, nrow=1, ncol=nrow(mat)),e=0)
eps = sqrt(.Machine$double.eps)
```

```{r}
for (k in seq_len(g$cc$n)) {
        i <- g$cc$nodes[[k]]
        print(i)
        n <- length(i)
        QQ <- mat[i, i, drop = FALSE]
        
        print(QQ)
        if (n == 1) {
            QQ[1, 1] <- 1
            marg.var[i] <- 1
        }
        else {
            cconstr <- constr
            if (!is.null(constr)) {
                cconstr$A <- constr$A[, i, drop = FALSE]
                eeps <- eps
            }
            else {
                eeps <- 0
            }
            idx.zero <- which(rowSums(abs(cconstr$A)) == 0)
            if (length(idx.zero) > 0) {
                cconstr$A <- cconstr$A[-idx.zero, , drop = FALSE]
                cconstr$e <- cconstr$e[-idx.zero]
            }

            res <- inla.qinv(QQ + Diagonal(n) * max(diag(QQ)) * 
                eeps, constr = cconstr)
            
            fac <- exp(mean(log(diag(res))))
            #print(res)
            
            print(fac)
            QQ <- fac * QQ
            marg.var[i] <- diag(res)/fac
        }
        
}
```















